<!-- Requirements  -->
<link href="css/ActivePersonalityView.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/ActivePersonalityView.js" type="text/javascript"></script>
<script src="js/Controls/ImageManager.js" type="text/javascript"></script>
<!-- Template -->
<script id="activePersonalityViewTemplate" type="text/x-jquery-tmpl">
    <div class="activePersonalityView">
      <div class="roundBackground"></div>
      
      <div class="backImages"></div>
      <img src="images/Personalities/${BaseIconID}.png" alt="" class="activePersonalityIcon" />
      <div class="frontImages"></div>
    </div>
</script>