<!-- Requirements  -->
<link href="css/AutoScrollingList.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/AutoScrollingList.js" type="text/javascript"></script>
<!--<link href="js/plugins/jquery-ui-1.8.11.custom/css/ui-lightness/jquery-ui-1.8.11.custom.css" rel="stylesheet" type="text/css" />
<script src="js/plugins/jquery-ui-1.8.11.custom/js/jquery-ui-1.8.11.custom.min.js" type="text/javascript"></script>-->
<!-- Template -->
<script id="autoScrollingListTemplate" type="text/x-jquery-tmpl">
	<div class="autoScrollingContainer">
    <span class="leftScroller"></span>
    <span class="rightScroller"></span>
    
    <div class="itemsContainer"></div>

  </div>
</script>