<!-- Requirements  -->
<link href="css/Baloon2.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/Baloon2.js" type="text/javascript"></script>

<!-- Template -->
<script id="baloon2Template" type="text/x-jquery-tmpl">
  <div class="baloon2Container">
    <img class="baloonBig" src="images/Intro/Controls/BalloonOrange.png" />
    <img class="baloonSmall" src="images/Intro/Controls/BalloonOrange.png" />    
  </div>
</script>