<!-- Requirements  -->
<link href="css/CallOut.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/CallOut.js" type="text/javascript"></script>

<!-- Templates -->
<script id="userCallOutTemplate" type="text/x-jquery-tmpl">
  <div class="callOutContainer userCallOut">
    <div class="whoContainer">You: </div>
    <div class="messageContainer"></div>
    <div class="roundedEdge userCallOutRoundedEdge"></div>
  </div>
</script>

<script id="chatmanCallOutTemplate" type="text/x-jquery-tmpl">  
  <div class="callOutContainer chatmanCallOut">
    <div class="roundedEdge chatmanCallOutRoundedEdge"></div>  
    <div class="whoContainer">Chatman: </div>
      <div class="messageContainer"></div>          
  </div>
</script>