<!-- Requirements  -->
<link href="css/ChatmanName.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/ChatmanName.js" type="text/javascript"></script>

<!-- Template -->
<script id="chatmanNameTemplate" type="text/x-jquery-tmpl">
  <div class="chatmanNameContainer">
    <div class="activePerconalityViewControl"></div>
    <div class="chatmanName">${Name}</div>
  </div>
</script>