<!-- Requirements  -->
<link href="css/ChatmanFigure.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/ChatmanFigure.js" type="text/javascript"></script>

<!-- Template -->
<script id="chatmanFigureTemplate" type="text/x-jquery-tmpl">
  <div class="chatmanFigureContainer">
    <img class="leftEyeBack" src="images/ChatmanFigure/Image72.png"></img>
    <img class="rightEyeBack" src="images/ChatmanFigure/Image75.png"></img>
    
    <img class="leftEye" src="images/ChatmanFigure/EyeLeft.png"></img>
    <img class="rightEye" src="images/ChatmanFigure/EyeRight.png"></img>
    
    <img class="leftHand" src="images/ChatmanFigure/Image78.png" clickCommand="HandsClick"></img>
    <img class="rightHand" src="images/ChatmanFigure/Image79.png" clickCommand="HandsClick"></img>
    
    <img class="leftEar" src="images/ChatmanFigure/Image82.png" clickCommand="EarsClick"></img>
    <img class="rightEar" src="images/ChatmanFigure/Image81.png" clickCommand="EarsClick"></img>

    <div class="eyelidsContainer">
      <img class="leftEyelid" src="images/ChatmanFigure/Image69.png"></img>
      <img class="rightEyelid" src="images/ChatmanFigure/Image70.png"></img>
    </div>

    <img class="chatmanBody" src="images/ChatmanFigure/Image84.png"></img>
    <div class="leftEyeClicker" clickCommand="EyesClick"></div>
    <div class="rightEyeClicker" clickCommand="EyesClick"></div>
    
    <div class="mouth" clickCommand="MouthClick"></div>
  </div>
</script>