<!-- Requirements  -->
<link href="css/CheckBox.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/CheckBox.js" type="text/javascript"></script>

<!-- Template -->
<script id="checkBoxTemplate" type="text/x-jquery-tmpl">
  <div class="checkBoxContainer">
    <div class="checkBox"></div>
    <div class="checkMark"></div>
    <span class="checkBoxText"></span>
  </div>
</script>