<!-- Requirements  -->
<link href="css/DatePicker.css" rel="stylesheet" type="text/css" />
<link href="js/Infrastructure/jquery-ui-1.8.14.custom.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/DatePicker.js" type="text/javascript"></script>
<script src="js/Infrastructure/jquery-ui-1.8.14.custom.min.js" type="text/javascript"></script>

<!-- Template -->
<script id="datePickerTemplate" type="text/x-jquery-tmpl">
  <div class="datePickerContainer">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="arrowColumn"></div>
    <input class="dateInput" type="text" />
  </div>
</script>