<!-- Requirements  -->
<link href="css/Flower1.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/Flower1.js" type="text/javascript"></script>

<!-- Template -->
<script id="flower1Template" type="text/x-jquery-tmpl">
  <div class="flower1Container">
	<img class="flower1Leaves" src="images/Intro/Controls/Flower1Body.png" />
	<img class="flower1Inner" src="images/Intro/Controls/Flower1Inner.png" />
	<img class="flower1Base" src="images/Intro/Controls/Flower1Base.png" />
  </div>
</script>