<!-- Requirements  -->
<link href="css/Flower3.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/Flower3.js" type="text/javascript"></script>

<!-- Template -->
<script id="flower3Template" type="text/x-jquery-tmpl">
  <div class="flower3Container">
	<img class="flower3Body" src="images/Intro/Controls/Flower3Body.png" />
	<img class="flower3Inner" src="images/Intro/Controls/Flower3Inner.png" />
	<img class="flower3Base" src="images/Intro/Controls/Flower3Base.png" />
  </div>
</script>