<!-- Requirements  -->
<link href="css/Flower2.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/Flower2.js" type="text/javascript"></script>

<!-- Template -->
<script id="flower2Template" type="text/x-jquery-tmpl">
  <div class="flower2Container">
	<img class="flower2Leaves" src="images/Intro/Controls/Flower2Leaves.png" />
	<img class="flower2Body" src="images/Intro/Controls/Flower2Body.png" />
	<img class="flower2Base" src="images/Intro/Controls/Flower2Base.png" />
  </div>
</script>