<!-- Requirements  -->
<link href="css/Flower4.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/Flower4.js" type="text/javascript"></script>

<!-- Template -->
<script id="flower4Template" type="text/x-jquery-tmpl">
  <div class="flower4Container">
	<img class="flower4Body" src="images/Intro/Controls/Flower4Body.png" />
	<img class="flower4Inner" src="images/Intro/Controls/Flower4Inner.png" />
	<img class="flower4Base" src="images/Intro/Controls/Flower4Base.png" />  
  </div>
</script>