<!-- Requirements  -->
<link href="css/FriendshipBar.css" rel="stylesheet" type="text/css" />
<script src="js/Infrastructure/LevelColor.js" type="text/javascript"></script>
<script src="js/Controls/FriendshipBar.js" type="text/javascript"></script>
<!-- Template -->
<script id="friendshipBarTemplate" type="text/x-jquery-tmpl">
    <div class="friendshipBar">
      <div class="friendshipBarLevel">
        <img class="triangle down" src="images/down.png" />
        <img class="triangle up" src="images/up.png" />
      </div>
    </div>
</script>