<!-- Requirements  -->
<link href="css/HorizontalBar.css" rel="stylesheet" type="text/css" />
<script src="js/Infrastructure/LevelColor.js" type="text/javascript"></script>
<script src="js/Controls/HorizontalBar.js" type="text/javascript"></script>

<!-- Template -->
<script id="horizontalBarTemplate" type="text/x-jquery-tmpl">
  <div class="horizontalBar">
    <div class="barLevel"></div>
  </div>
</script>