<!-- Requirements  -->
<link href="css/InfoMenu.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/InfoMenu.js" type="text/javascript"></script>

<!-- Template -->
<script id="infoMenuTemplate" type="text/x-jquery-tmpl">
  
  <div class="infoMenuContainer">
    <ul class="infoMenu">
      <li class="infoTitle">
        <div id="TextBlock_1">Description</div>
      </li>
      <li id="descriptionInfo"></li>
      <li>
        <hr class="line" />
      </li>
      <li class="infoTitle">
        <div id="TextBlock_3">Designer</div>
      </li>
      <li id="designerInfo"></li>
      <li>
        <hr class="line" />
      </li>
      <li id="scope"></li>
    </ul>  
  </div>  
  
</script>