<!-- Requirements  -->
<link href="css/MainPanelButtons.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/MainPanelButtons.js" type="text/javascript"></script>
<!-- Template -->
<script id="mainPanelButtonsTemplate" type="text/x-jquery-tmpl">  
  <div id="mainPanelButtonsContainer">
    
    <div class="panelButtonContainer">
      <div id="chatWithChatmanButton" class="mainPanelButton"  role="NavigateChatWithChatman">
        <img src="images/ChatWithChatman.png" class="panelButtonImage" />
      </div>
    </div>

    <div class="panelButtonContainer">
      <div id="personalitiesButton" class="mainPanelButton"  role="NavigatePersonalities">
        <img src="images/Personalities.png" class="panelButtonImage"/>
      </div>
    </div>

    <div class="panelButtonContainer">
      <div id="gamesButton" class="mainPanelButton"  role="NavigateGamesAndMore">
        <img src="images/GamesMore.png" class="panelButtonImage"/>
      </div>
    </div>

    <div class="panelButtonContainer">
      <div id="chatWithFriendsButton" class="mainPanelButton"  role="NavigateChatWithFriends">
        <img src="images/ChatWithFriends.png" class="panelButtonImage"/>
      </div>
    </div>

    <div class="panelButtonContainer">
      <div id="remindersButton" class="mainPanelButton"  role="NavigateReminders">
        <img src="images/Reminders.png" class="panelButtonImage"/>
      </div>
    </div>

    <div class="panelButtonContainer">
      <div id="appsDownloadsButton" class="mainPanelButton" role="NavigateAppsAndDownloads">
        <img src="images/AppsDownloads.png" class="panelButtonImage"/>
      </div>
    </div>
  </div>  
</script>
