<!-- Requirements  -->
<link href="css/MoodGraphicalDisplay.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/MoodGraphicalDisplay.js" type="text/javascript"></script>
<!-- Template -->
<script id="moodItemTemplate" type="text/x-jquery-tmpl">
  <div class="moodItemContainer">
    <img src="images/Moods/${MoodName}.png" class="moodImage" />
    <div class="moodName">${MoodName}</div>
  </div>
</script>