<!-- Requirements  -->
<link href="css/MultySelectionList.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/MultySelectionList.js" type="text/javascript"></script>
<!--<link href="js/plugins/jquery-ui-1.8.11.custom/css/ui-lightness/jquery-ui-1.8.11.custom.css" rel="stylesheet" type="text/css" />
<script src="js/plugins/jquery-ui-1.8.11.custom/js/jquery-ui-1.8.11.custom.min.js" type="text/javascript"></script>-->

<!-- Template -->
<script id="multySelectionListTemplate" type="text/x-jquery-tmpl">
	<div class="multySelectContainer">
    <span class="leftScroller"></span>
    <span class="rightScroller"></span>
    
    <div class="itemsContainer"></div>

    <!--<div class="slider">      
    </div>-->

  </div>
</script>