<!-- Requirements  -->
<link href="css/RecorderVolumeControl.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/RecorderVolumeControl.js" type="text/javascript"></script>
<!-- Template -->
<script id="recorderVolumeControlTemplate" type="text/x-jquery-tmpl">
  <div id="recorderVolumeControl">
    <img src="images/microphone.gif"/>
    <div id="scaleContainer">
      <div id="onColor"></div>
      <div id="scaleGrid"></div>
    </div>

    <div class="disablingArea"></div>
  </div>
</script>