<!-- Requirements  -->
<link href="css/RegisterMessageControl.css" rel="stylesheet" type="text/css" />
<script src="js/Infrastructure/string.format-1.0.packed.js" type="text/javascript"></script>
<script src="js/Controls/RegisterMessage.js" type="text/javascript"></script>

<!-- Template -->
<script id="registerMessageTemplate" type="text/x-jquery-tmpl">
  <div class="myChatmanArea">
    <div class="importantText">
      <img class="exclamationImage" src="images/registration-popup.png" />
      <div class="attentionText">
        <span>Attention!</span>  
      </div>      
    </div>
    <div class="text"></div>
    <div class="buttons">
      <div class="registerButton pushButtonBlue">REGISTER</div>
      <div class="notNowButton pushButtonRed">NOT NOW</div>
    </div>
  </div>
</script>