<!-- Requirements  -->
<link href="css/SelectableImage.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/SelectableImage.js" type="text/javascript"></script>

<!-- Template -->
<script id="selectableImageTemplate" type="text/x-jquery-tmpl">
  <div class="selectableImage">    
    <div class="roundBackground"></div>    
    <img class="image" src="images/Personalities/BIG/${ImageName}.png" alt=""  />
  </div>
</script>