<!-- Requirements  -->
<link href="css/WaitOverlap.css" rel="stylesheet" type="text/css" />
<script src="js/Controls/WaitOverlap.js" type="text/javascript"></script>

<!-- Template -->
<script id="waitOverlapTemplate" type="text/x-jquery-tmpl">
  <div class="waitOverlapContainer">
    <div class="backgroundOverlap"></div>
    <div class="waitMessageContainer">
      <div class="waitText">Please wait...</div>
      <div class="waitImageContainer"><img src="images/loading_bar.gif" /></div>
    </div>    
  </div>
</script>