var ControlsResourceStrings = {    
    MoodNotSet: "",
    MoodPretty: "Pretty",
    MoodVery: "Very",
    MoodLittle: "A little",
    MoodBit: "A bit",
    PrivateScope: "Private!",
    PublicScope: "Public!",
    AudioCanHearText: "Can hear you OK",
    AudioCantHearText: "Can't hear you!",
    
    ParentsAreaCheckBox0: "Don't allow new content creation or content editing",
    ParentsAreaCheckBox1: "Don't allow new content sharing",
    ParentsAreaCheckBox2: "Don't allow new content download",
    ParentsAreaCheckBox3: "Don't allow new content preview",
    
    RemindersOneTimeOnly: "ONCE",
	RemindersDays: "EVERY DAY",
	RemindersWeeks: "EVERY WEEK",
	RemindersMonths: "EVERY MONTH",
	RemindersYears: "EVERY YEAR",
	
	/*AddWordCallout2: "ADD WORD",
	AddWordCallout1: "Teach me:",*/
	AddWordCallout1: "A word or a question?",
	AddWordCallout2: "ADD WORD",
	AddWordCallout3: "TEACH QUESTION",
	AddChitChatCallout1: "No chit chats!",
	AddChitChatCallout2: "NEW CHIT CHAT",
	GoCallout: "Go!",
	SearchOrTeachCallout1: "Don't know?",
	SearchOrTeachCallout2: "SEARCH",
	SearchOrTeachCallout3: "TEACH ANSWER",
	TeachCallout1: "Don't know?",
	TeachCallout2: "TEACH ANSWER",
	YesNoQuestionCallout1: "I don't know...",
	YesNoQuestionCallout2: "YES",
	YesNoQuestionCallout3: "NO",
	UserProfileOrTeachCallout1: "Teach me...",
	UserProfileOrTeachCallout2: "ABOUT ME",
	UserProfileOrTeachCallout3: "TEACH ANSWER",
	
	ProactiveRemindersCallout1: "SET REMINDERS",
	CinemaAndGamesCallout1: "CHATMAN CINEMA",
	CinemaAndGamesCallout2: "PLAY GAMES",
	RegistrationCallout: "REGISTER",
	PersonalitiesCallout: "CHATMAN PERSONALITIES",
	DownloadChitChatCallout: "DOWNLOAD CHIT CHAT",
	ShowAllTeachCallout1: "NEW CHIT CHAT",
	ShowAllTeachCallout2: "NEW WORDS",
	ShowAllTeachCallout3: "TEACH QUESTION",
	
	HomeworkOrGamesOrCinemaCallout1: "HOMEWORK HELP",
	HomeworkOrGamesOrCinemaCallout2: "PLAY GAMES",
	HomeworkOrGamesOrCinemaCallout3: "CHATMAN CINEMA",
	GoToHomeworkCallout1: "HOMEWORK HELP"
}
